### ISSUE TITLE
点点券前面几个号，又开始报错了

### ISSUE THREAD

**Issue by Annyoo2021** [photonmang/quantumultX#21]

**Comment by Annyoo2021** [comment]
点点券, 错误!
TypeError: Cannot read property '1' of null
    at ZooFakerNecklace.run (/jd/scripts/jd_necklace.js:58:47)
    at async getBody (/jd/scripts/jd_necklace.js:186:17)
    at async sign (/jd/scripts/jd_necklace.js:298:14)
    at async jd_necklace (/jd/scripts/jd_necklace.js:242:5)
    at async /jd/scripts/jd_necklace.js:225:7

**Comment by photonmang** [comment]
将JDJRValidator文件放到scripts下后再执行一次

**Comment by Annyoo2021** [comment]
好吧谢谢，可这个文件一直都有的。

**Comment by photonmang** [comment]
也可能是你的网络问题。我这边运行没有问题！建议可以重启机器试试
