### ISSUE TITLE
necklace修复是对账号是数字-数字这类账号有BUG

### ISSUE THREAD

**Issue by Acr05s** [photonmang/quantumultX#23]
似乎是账号蹭有“-”连接符会报错，“_”连接的都没问题。
点点券, 错误!
TypeError: Cannot read property '1' of null
    at ZooFakerNecklace.run (/ql/scripts/photonmang_quantumultX_jd_necklace.js:58:47)
    at async getBody (/ql/scripts/photonmang_quantumultX_jd_necklace.js:186:17)
    at async doTask (/ql/scripts/photonmang_quantumultX_jd_necklace.js:271:16)
    at async jd_necklace (/ql/scripts/photonmang_quantumultX_jd_necklace.js:241:5)
    at async /ql/scripts/photonmang_quantumultX_jd_necklace.js:225:7

**Comment by Acr05s** [comment]
修必42行的正则表达式，已解决  修改  \w+? ---->  \w+?\-\w+

**Comment by Annyoo2021** [comment]
我前面3个号，也一直这问题。后面的都正常

**Comment by Annyoo2021** [comment]
好像都不行了。大佬什么时候修修啊。。。网络没问题

【点击券后9.9】 任务未领取,开始领取此任务
ZooFakerNecklace: 411.541ms
领取任务结果：{"rtn_code":403,"rtn_msg":"非法请求！"}
【点击券后9.9】 任务领取成功,开始完成此任务
需等待30秒
点击“券后9.9”任务:{"code":"600","echo":"signature verification failed"}
【浏览精选活动】 任务未领取,开始领取此任务
领取任务结果：{"rtn_code":403,"rtn_msg":"非法请求！"}
【浏览精选活动】 任务领取成功,开始完成此任务
【玩锦鲤红包】 任务未领取,开始领取此任务
领取任务结果：{"rtn_code":403,"rtn_msg":"非法请求！"}
【玩锦鲤红包】 任务领取成功,开始完成此任务
做任务结果：{"data":{"biz_code":1002,"biz_msg":"用户未领取该任务"},"rtn_code":0,"rtn_msg":"请求成功！"}
【玩拼券活动】 任务未领取,开始领取此任务
领取任务结果：{"rtn_code":403,"rtn_msg":"非法请求！"}
【玩拼券活动】 任务领取成功,开始完成此任务
做任务结果：{"data":{"biz_code":1002,"biz_msg":"用户未领取该任务"},"rtn_code":0,"rtn_msg":"请求成功！"}
【逛券后9.9】 任务未领取,开始领取此任务
领取任务结果：{"rtn_code":403,"rtn_msg":"非法请求！"}
【逛券后9.9】 任务领取成功,开始完成此任务
做任务结果：{"data":{"biz_code":1002,"biz_msg":"用户未领取该任务"},"rtn_code":0,"rtn_msg":"请求成功！"}
【去买省钱券包】 任务未领取,开始领取此任务
领取任务结果：{"rtn_code":403,"rtn_msg":"非法请求！"}
【去买省钱券包】 任务领取成功,开始完成此任务
做任务结果：{"data":{"biz_code":1002,"biz_msg":"用户未领取该任务"},"rtn_code":0,"rtn_msg":"请求成功！"}

开始每日签到
每日签到失败：{"rtn_code":403,"rtn_msg":"非法请求！"}
